/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Minimal STM32F0 register map used by this firmware. */
typedef struct
{
    volatile uint32_t MODER;
    volatile uint32_t OTYPER;
    volatile uint32_t OSPEEDR;
    volatile uint32_t PUPDR;
    volatile uint32_t IDR;
    volatile uint32_t ODR;
    volatile uint32_t BSRR;
    volatile uint32_t LCKR;
    volatile uint32_t AFR[2];
    volatile uint32_t BRR;
} GPIO_TypeDef;

typedef struct
{
    volatile uint32_t CR;
    volatile uint32_t CFGR;
    volatile uint32_t CIR;
    volatile uint32_t ACR;
    volatile uint32_t RESERVED;
    volatile uint32_t KEYR;
    volatile uint32_t OPTKEYR;
    volatile uint32_t SR;
    volatile uint32_t CR2;
    volatile uint32_t AR;
    volatile uint32_t OBR;
    volatile uint32_t WRPR;
} FLASH_TypeDef;

typedef struct
{
    volatile uint32_t CR;
    volatile uint32_t CFGR;
    volatile uint32_t CIR;
    volatile uint32_t APB2RSTR;
    volatile uint32_t APB1RSTR;
    volatile uint32_t AHBENR;
    volatile uint32_t APB2ENR;
    volatile uint32_t APB1ENR;
    volatile uint32_t BDCR;
    volatile uint32_t CSR;
    volatile uint32_t AHBRSTR;
    volatile uint32_t CFGR2;
    volatile uint32_t CFGR3;
    volatile uint32_t CR2;
} RCC_TypeDef;

typedef struct
{
    volatile uint32_t CR1;
    volatile uint32_t CR2;
    volatile uint32_t SMCR;
    volatile uint32_t DIER;
    volatile uint32_t SR;
    volatile uint32_t EGR;
    volatile uint32_t CCMR1;
    volatile uint32_t CCMR2;
    volatile uint32_t CCER;
    volatile uint32_t CNT;
    volatile uint32_t PSC;
    volatile uint32_t ARR;
    volatile uint32_t RCR;
    volatile uint32_t CCR1;
    volatile uint32_t CCR2;
    volatile uint32_t CCR3;
    volatile uint32_t CCR4;
    volatile uint32_t BDTR;
    volatile uint32_t DCR;
    volatile uint32_t DMAR;
    volatile uint32_t OR;
} TIM_TypeDef;

typedef struct
{
    volatile uint32_t CCR;
    volatile uint32_t CNDTR;
    volatile uint32_t CPAR;
    volatile uint32_t CMAR;
    volatile uint32_t RESERVED;
} DMA_Channel_TypeDef;

typedef struct
{
    volatile uint32_t ISR;
    volatile uint32_t IFCR;
    DMA_Channel_TypeDef CHANNEL[5];
} DMA_TypeDef;

#define RCC_BASE (0x40021000UL)
#define FLASH_BASE (0x40022000UL)
#define GPIOB_BASE (0x48000400UL)
#define TIM17_BASE (0x40014800UL)
#define DMA1_BASE (0x40020000UL)

#define FLASH ((FLASH_TypeDef *)FLASH_BASE)
#define RCC ((RCC_TypeDef *)RCC_BASE)
#define GPIOB ((GPIO_TypeDef *)GPIOB_BASE)
#define TIM17 ((TIM_TypeDef *)TIM17_BASE)
#define DMA1 ((DMA_TypeDef *)DMA1_BASE)
#define DMA1_CHANNEL1 (&DMA1->CHANNEL[0])

#define FLASH_ACR_LATENCY (1UL << 0)
#define FLASH_ACR_PRFTBE (1UL << 4)

#define RCC_CR_HSION (1UL << 0)
#define RCC_CR_HSIRDY (1UL << 1)
#define RCC_CR_PLLON (1UL << 24)
#define RCC_CR_PLLRDY (1UL << 25)

#define RCC_CFGR_SW_HSI (0UL << 0)
#define RCC_CFGR_SW_PLL (2UL << 0)
#define RCC_CFGR_SWS_MASK (3UL << 2)
#define RCC_CFGR_SWS_HSI (0UL << 2)
#define RCC_CFGR_SWS_PLL (2UL << 2)
#define RCC_CFGR_HPRE_DIV1 (0UL << 4)
#define RCC_CFGR_PPRE_DIV1 (0UL << 8)
#define RCC_CFGR_PLLSRC_HSI_DIV2 (0UL << 15)
#define RCC_CFGR_PLLMUL_MASK (0xFUL << 18)
#define RCC_CFGR_PLLMUL_X12 (10UL << 18)

#define RCC_AHBENR_DMA1EN (1UL << 0)
#define RCC_AHBENR_GPIOBEN (1UL << 18)
#define RCC_APB2ENR_TIM17EN (1UL << 18)

#define TIM_CR1_CEN (1UL << 0)
#define TIM_CR1_ARPE (1UL << 7)
#define TIM_DIER_UDE (1UL << 8)
#define TIM_EGR_UG (1UL << 0)
#define TIM_CCMR1_OC1M_PWM1 (6UL << 4)
#define TIM_CCER_CC1E (1UL << 0)
#define TIM_BDTR_MOE (1UL << 15)

#define DMA_CCR_EN (1UL << 0)
#define DMA_CCR_TCIE (1UL << 1)
#define DMA_CCR_TEIE (1UL << 3)
#define DMA_CCR_DIR (1UL << 4)
#define DMA_CCR_MINC (1UL << 7)
#define DMA_CCR_PSIZE_16 (1UL << 8)
#define DMA_CCR_MSIZE_16 (1UL << 10)
#define DMA_CCR_PL_HIGH (2UL << 12)

#define DMA_ISR_TCIF1 (1UL << 1)
#define DMA_ISR_TEIF1 (1UL << 3)
#define DMA_IFCR_CGIF1 (1UL << 0)
#define DMA_IFCR_CTCIF1 (1UL << 1)
#define DMA_IFCR_CHTIF1 (1UL << 2)
#define DMA_IFCR_CTEIF1 (1UL << 3)

#define DMA1_CH1_IRQn (9U)

#define NVIC_ISER0 (*(volatile uint32_t *)0xE000E100UL)
#define NVIC_ICPR0 (*(volatile uint32_t *)0xE000E280UL)

/* SYSCLK = 48 MHz. With ARR=59, PWM period = 60 ticks = 1.25 us (800 kHz). */
#define WS2812_TIMER_PERIOD_TICKS (60U)
#define WS2812_T0H_TICKS (20U)
#define WS2812_T1H_TICKS (40U)

#define WS2812_LED_BITS (24U)
#define WS2812_RESET_SLOTS (64U)
#define WS2812_FRAME_SLOTS (WS2812_LED_BITS + WS2812_RESET_SLOTS)

static uint16_t ws2812_frame[WS2812_FRAME_SLOTS];
static volatile uint8_t ws2812_dma_busy = 0U;
static volatile uint8_t ws2812_dma_error = 0U;

static void ws2812_dma_finalize(uint32_t status)
{
    if ((status & DMA_ISR_TEIF1) != 0U)
    {
        ws2812_dma_error = 1U;
    }

    DMA1_CHANNEL1->CCR &= ~DMA_CCR_EN;
    DMA1->IFCR = DMA_IFCR_CGIF1 | DMA_IFCR_CTCIF1 | DMA_IFCR_CHTIF1 | DMA_IFCR_CTEIF1;

    TIM17->CCR1 = 0U;
    TIM17->CR1 &= ~TIM_CR1_CEN;
    TIM17->CNT = 0U;
    ws2812_dma_busy = 0U;
}
void SystemInit(void)
{
    /* Ensure Flash latency matches 48 MHz operation. */
    FLASH->ACR = FLASH_ACR_PRFTBE | FLASH_ACR_LATENCY;

    /* Ensure HSI is on and selected as temporary system clock. */
    RCC->CR |= RCC_CR_HSION;
    while ((RCC->CR & RCC_CR_HSIRDY) == 0U)
    {
    }

    RCC->CFGR &= ~(3UL << 0);
    RCC->CFGR |= RCC_CFGR_SW_HSI;
    while ((RCC->CFGR & RCC_CFGR_SWS_MASK) != RCC_CFGR_SWS_HSI)
    {
    }

    /* Configure bus prescalers and PLL (HSI/2 * 12 = 48 MHz). */
    RCC->CR &= ~RCC_CR_PLLON;
    while ((RCC->CR & RCC_CR_PLLRDY) != 0U)
    {
    }

    RCC->CFGR &= ~((0xFUL << 4) | (0x7UL << 8) | (1UL << 15) | RCC_CFGR_PLLMUL_MASK);
    RCC->CFGR |= RCC_CFGR_HPRE_DIV1 | RCC_CFGR_PPRE_DIV1 | RCC_CFGR_PLLSRC_HSI_DIV2 | RCC_CFGR_PLLMUL_X12;

    RCC->CR |= RCC_CR_PLLON;
    while ((RCC->CR & RCC_CR_PLLRDY) == 0U)
    {
    }

    RCC->CFGR &= ~(3UL << 0);
    RCC->CFGR |= RCC_CFGR_SW_PLL;
    while ((RCC->CFGR & RCC_CFGR_SWS_MASK) != RCC_CFGR_SWS_PLL)
    {
    }
}

static void delay_cycles(volatile uint32_t cycles)
{
    while (cycles--)
    {
        __asm volatile("nop");
    }
}

static void ws2812_gpio_init_pb9_tim17_ch1(void)
{
    RCC->AHBENR |= RCC_AHBENR_GPIOBEN;

    /* PB9 in alternate function mode, AF2 = TIM17_CH1 on STM32F072. */
    GPIOB->MODER &= ~(3UL << (9U * 2U));
    GPIOB->MODER |= (2UL << (9U * 2U));

    GPIOB->OTYPER &= ~(1UL << 9U);

    GPIOB->OSPEEDR &= ~(3UL << (9U * 2U));
    GPIOB->OSPEEDR |= (3UL << (9U * 2U));

    GPIOB->PUPDR &= ~(3UL << (9U * 2U));

    GPIOB->AFR[1] &= ~(0xFUL << ((9U - 8U) * 4U));
    GPIOB->AFR[1] |= (0x2UL << ((9U - 8U) * 4U));
}

static void ws2812_tim17_pwm_dma_init(void)
{
    RCC->AHBENR |= RCC_AHBENR_DMA1EN;
    RCC->APB2ENR |= RCC_APB2ENR_TIM17EN;

    TIM17->CR1 = TIM_CR1_ARPE;
    TIM17->PSC = 0U;
    TIM17->ARR = WS2812_TIMER_PERIOD_TICKS - 1U;
    TIM17->CCR1 = 0U;
    TIM17->CCMR1 = TIM_CCMR1_OC1M_PWM1;
    TIM17->CCER = TIM_CCER_CC1E;
    TIM17->BDTR = TIM_BDTR_MOE;
    TIM17->DIER = TIM_DIER_UDE;
    TIM17->EGR = TIM_EGR_UG;

    DMA1_CHANNEL1->CCR = 0U;
    DMA1_CHANNEL1->CPAR = (uint32_t)&TIM17->CCR1;

    NVIC_ICPR0 = (1UL << DMA1_CH1_IRQn);
    NVIC_ISER0 = (1UL << DMA1_CH1_IRQn);
}

static void ws2812_encode_grb(uint8_t red, uint8_t green, uint8_t blue)
{
    uint32_t grb = ((uint32_t)green << 16) | ((uint32_t)red << 8) | (uint32_t)blue;

    for (uint32_t bit = 0U; bit < WS2812_LED_BITS; ++bit)
    {
        uint32_t mask = 1UL << (23U - bit);
        ws2812_frame[bit] = (grb & mask) ? WS2812_T1H_TICKS : WS2812_T0H_TICKS;
    }

    for (uint32_t slot = WS2812_LED_BITS; slot < WS2812_FRAME_SLOTS; ++slot)
    {
        ws2812_frame[slot] = 0U;
    }
}

static void ws2812_send_frame_dma_it(void)
{
    if (ws2812_dma_busy != 0U)
    {
        return;
    }

    ws2812_dma_busy = 1U;
    ws2812_dma_error = 0U;

    DMA1_CHANNEL1->CCR &= ~DMA_CCR_EN;
    DMA1->IFCR = DMA_IFCR_CGIF1 | DMA_IFCR_CTCIF1 | DMA_IFCR_CHTIF1 | DMA_IFCR_CTEIF1;

    TIM17->CR1 &= ~TIM_CR1_CEN;
    TIM17->CNT = 0U;
    TIM17->CCR1 = ws2812_frame[0];

    DMA1_CHANNEL1->CMAR = (uint32_t)&ws2812_frame[1];
    DMA1_CHANNEL1->CNDTR = WS2812_FRAME_SLOTS - 1U;
    DMA1_CHANNEL1->CCR = DMA_CCR_DIR | DMA_CCR_MINC | DMA_CCR_PSIZE_16 | DMA_CCR_MSIZE_16 | DMA_CCR_PL_HIGH | DMA_CCR_TCIE | DMA_CCR_TEIE;

    TIM17->CR1 |= TIM_CR1_CEN;
    DMA1_CHANNEL1->CCR |= DMA_CCR_EN;
}

void DMA1_CH1_IRQHandler(void)
{
    uint32_t status = DMA1->ISR;

    if ((status & (DMA_ISR_TCIF1 | DMA_ISR_TEIF1)) != 0U)
    {
        ws2812_dma_finalize(status);
    }
}

static uint8_t ws2812_set_rgb(uint8_t red, uint8_t green, uint8_t blue)
{
    if (ws2812_dma_busy != 0U)
    {
        return 0U;
    }

    ws2812_encode_grb(red, green, blue);
    ws2812_send_frame_dma_it();

    return 1U;
}

int main(void)
{
    uint8_t color_index = 0U;

    ws2812_gpio_init_pb9_tim17_ch1();
    ws2812_tim17_pwm_dma_init();

    /* Ensure global IRQs are enabled for DMA completion callback. */
    __asm volatile("cpsie i");

    while (1)
    {
        if (ws2812_dma_busy != 0U)
        {
            uint32_t dma_status = DMA1->ISR;
            if ((dma_status & (DMA_ISR_TCIF1 | DMA_ISR_TEIF1)) != 0U)
            {
                /* Fallback in case DMA IRQ is masked: keep state machine running. */
                ws2812_dma_finalize(dma_status);
            }

            continue;
        }

        if (ws2812_dma_error != 0U)
        {
            ws2812_dma_error = 0U;
        }

        if (color_index == 0U)
        {
            (void)ws2812_set_rgb(24U, 0U, 0U);
        }
        else if (color_index == 1U)
        {
            (void)ws2812_set_rgb(0U, 24U, 0U);
        }
        else
        {
            (void)ws2812_set_rgb(0U, 0U, 24U);
        }

        color_index++;
        if (color_index >= 3U)
        {
            color_index = 0U;
        }

        delay_cycles(6000000U);
    }
}
